### ISSUE TITLE
Provide updated Mac install instructions

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity-admindocs#5]
Singularity Desktop for Mac is no longer updated. Provide instructions for vagrant on Mac.

**Comment by MaxCan-Code** [comment]
How about instructions for Docker on Mac/Windows? I have a working [`compose.yaml`](../../../MaxCan-Code/thesis/blob/main/compose.yaml) using the latest image on quay.io
```yaml
services:
  singularity:
    image: quay.io/singularity/singularity:v3.7.4-slim 
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - .:/root
    entrypoint: ["/bin/sh"]
```
, which is a slimmed down verson of https://github.com/horothesun/singularity-conda-multiple-envs#-local-singularity-image-build. I can add the instructions if you'd like
